//= include '../../bower_components/prism/prism.js'
//= include '../../bower_components/prism/components/prism-bash.js'
//= include '../../bower_components/prism/components/prism-css.js'
//= include '../../bower_components/prism/components/prism-sql.js'
//= include './prism-yaml.js'
//= include './prism-json.js'
//= include './prism-hql.js'
//= include './prism-ts.js'
