#!/bin/bash

root=$(dirname $(dirname $0))
dist="$root/heroic-dist"

CLASSPATH=

JVM_OPTS=${JVM_OPTS:-""}

if [[ $1 == '-debug' ]]; then
    JVM_OPTS="$JVM_OPTS -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
    shift
fi

if [[ -d $dist ]]; then
    jar="$dist/target/heroic-dist-0.0.1-SNAPSHOT-shaded.jar"

    if [[ ! -f $jar ]]; then
        (cd $root && mvn clean package)
    fi

    if [[ ! -f $jar ]]; then
        echo "No such jar: $jar" 1>&2
        exit 1
    fi

    CLASSPATH="$root/heroic-dist/target/heroic-dist-0.0.1-SNAPSHOT-shaded.jar"
fi

exec env CLASSPATH="$CLASSPATH" java $JVM_OPTS com.spotify.heroic.HeroicShell "$@"
