baseurl: /heroic
collections_dir: content
collections:
  docs:
    output: true
  tutorials:
    output: true
  endpoints:
    output: true
    permalink: /docs/api/:name
  api_types:
    output: true
    permalink: /docs/api/types/:name
  fault_tree:
    output: true
    permalink: /docs/fta/:name

defaults:
  - scope:
      type: docs
    values:
      layout: sidebar
  - scope:
      type: tutorials
    values:
      layout: default
  - scope:
      type: endpoints
    values:
      layout: api-endpoint
      responses:
        - status: 200
  - scope:
      type: api_types
    values:
      layout: api-type
  - scope:
      type: fault_tree
    values:
      layout: fault-tree

sass:
  sass_dir: assets/_sass
  style: compressed
